vich_uploader:
    db_driver: orm

    mappings:
       articles_images:
            uri_prefix: '%app.path.articles_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.articles_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

       references_images:
            uri_prefix: '%app.path.references_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.references_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

       services_images:
         uri_prefix: '%app.path.services_images%'
         upload_destination: '%kernel.project_dir%/public%app.path.services_images%'
         namer: Vich\UploaderBundle\Naming\UniqidNamer